// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ssIpLVC0ob0lWVM5t6j_ohsTrclsHCc',
    appId: '1:719955090524:web:e236073bebcc4f60f89a99',
    messagingSenderId: '719955090524',
    projectId: 'daandn-app',
    authDomain: 'daandn-app.firebaseapp.com',
    storageBucket: 'daandn-app.appspot.com',
    measurementId: 'G-FJBVEQ8N2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkfRDgNIEdxZXvbon6CPRNiPyf6jqz5ns',
    appId: '1:719955090524:android:0eb1c68c8b403651f89a99',
    messagingSenderId: '719955090524',
    projectId: 'daandn-app',
    storageBucket: 'daandn-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd_H7mzpcKhB07lW9OIsrHyC28trs7IVc',
    appId: '1:719955090524:ios:d00328293749b841f89a99',
    messagingSenderId: '719955090524',
    projectId: 'daandn-app',
    storageBucket: 'daandn-app.appspot.com',
    iosBundleId: 'com.example.fastAppBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd_H7mzpcKhB07lW9OIsrHyC28trs7IVc',
    appId: '1:719955090524:ios:d00328293749b841f89a99',
    messagingSenderId: '719955090524',
    projectId: 'daandn-app',
    storageBucket: 'daandn-app.appspot.com',
    iosBundleId: 'com.example.fastAppBase',
  );
}
